version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
    command: >
      bash -c "flask db upgrade && 
      gunicorn --bind 0.0.0.0:5000 --workers 3 --timeout 120 'backend.wsgi:app'"

  # Optional: Uncomment if using a frontend service
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:80"
  #   restart: unless-stopped
  #   depends_on:
  #     - web

volumes:
  postgres_data: 